name: Test and Deploy

on:
  push:
    branches: [ main ]
    paths-ignore: 
      - '**/README.md'
      - '**/*.yml'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
env:
  AZURE_FUNCTIONAPP_NAME: dotnet5-test-app # set this to the name of your azure function app resource
  AZURE_FUNCTION_PROJ_PATH: src/Sample.FunctionApp  # set this to the path to your function app project
  ROOT_SOLUTION_PATH: src # set this to the root path of your solution/project file

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Authenticate to Azure as a Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS_FUNCTION_APP }}
    
      - name: Get the latest source code commit
        uses: actions/checkout@v2
      
      - name: List project files before build.settings.json rename
        run: tree
        working-directory: ${{ env.AZURE_FUNCTION_PROJ_PATH }}
        
      - name: Rename build.settings.json to local.settings.json
        run: mv build.settings.json local.settings.json
        working-directory: ${{ env.AZURE_FUNCTION_PROJ_PATH }}
      
      - name: List project files after build.settings.json rename
        run: tree
        working-directory: ${{ env.AZURE_FUNCTION_PROJ_PATH }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ${{ env.ROOT_SOLUTION_PATH }}

      - name: Build for Testing
        run: dotnet build --no-restore
        working-directory: ${{ env.ROOT_SOLUTION_PATH }}
      
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: ${{ env.ROOT_SOLUTION_PATH }}
      
      - name: Clean debug configuration output
        run: dotnet clean
        working-directory: ${{ env.ROOT_SOLUTION_PATH }}
      
      - name: Build Function App for Release
        run: dotnet build --configuration Release --output ./output
        working-directory: ${{ env.AZURE_FUNCTION_PROJ_PATH }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTION_PROJ_PATH }}/output'
          publish-profile: ${{ secrets.AZURE_FUNCTION_PUBLISH_CREDS }}
